/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PositionService } from "../position.service";
import { PositionCreateInput } from "./PositionCreateInput";
import { Position } from "./Position";
import { PositionFindManyArgs } from "./PositionFindManyArgs";
import { PositionWhereUniqueInput } from "./PositionWhereUniqueInput";
import { PositionUpdateInput } from "./PositionUpdateInput";
import { ApplicantFindManyArgs } from "../../applicant/base/ApplicantFindManyArgs";
import { Applicant } from "../../applicant/base/Applicant";
import { ApplicantWhereUniqueInput } from "../../applicant/base/ApplicantWhereUniqueInput";

export class PositionControllerBase {
  constructor(protected readonly service: PositionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Position })
  async createPosition(
    @common.Body() data: PositionCreateInput
  ): Promise<Position> {
    return await this.service.createPosition({
      data: data,
      select: {
        description: true,
        id: true,
        notes: true,
        priority: true,
        recruiter: true,
        status: true,
        title: true,
        vacancies: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Position] })
  @ApiNestedQuery(PositionFindManyArgs)
  async positions(@common.Req() request: Request): Promise<Position[]> {
    const args = plainToClass(PositionFindManyArgs, request.query);
    return this.service.positions({
      ...args,
      select: {
        description: true,
        id: true,
        notes: true,
        priority: true,
        recruiter: true,
        status: true,
        title: true,
        vacancies: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Position })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async position(
    @common.Param() params: PositionWhereUniqueInput
  ): Promise<Position | null> {
    const result = await this.service.position({
      where: params,
      select: {
        description: true,
        id: true,
        notes: true,
        priority: true,
        recruiter: true,
        status: true,
        title: true,
        vacancies: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Position })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePosition(
    @common.Param() params: PositionWhereUniqueInput,
    @common.Body() data: PositionUpdateInput
  ): Promise<Position | null> {
    try {
      return await this.service.updatePosition({
        where: params,
        data: data,
        select: {
          description: true,
          id: true,
          notes: true,
          priority: true,
          recruiter: true,
          status: true,
          title: true,
          vacancies: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Position })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePosition(
    @common.Param() params: PositionWhereUniqueInput
  ): Promise<Position | null> {
    try {
      return await this.service.deletePosition({
        where: params,
        select: {
          description: true,
          id: true,
          notes: true,
          priority: true,
          recruiter: true,
          status: true,
          title: true,
          vacancies: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/applicants")
  @ApiNestedQuery(ApplicantFindManyArgs)
  async findApplicants(
    @common.Req() request: Request,
    @common.Param() params: PositionWhereUniqueInput
  ): Promise<Applicant[]> {
    const query = plainToClass(ApplicantFindManyArgs, request.query);
    const results = await this.service.findApplicants(params.id, {
      ...query,
      select: {
        email: true,
        id: true,
        name: true,
        phone: true,

        position: {
          select: {
            id: true,
          },
        },

        resume: true,
        status: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/applicants")
  async connectApplicants(
    @common.Param() params: PositionWhereUniqueInput,
    @common.Body() body: ApplicantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applicants: {
        connect: body,
      },
    };
    await this.service.updatePosition({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/applicants")
  async updateApplicants(
    @common.Param() params: PositionWhereUniqueInput,
    @common.Body() body: ApplicantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applicants: {
        set: body,
      },
    };
    await this.service.updatePosition({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/applicants")
  async disconnectApplicants(
    @common.Param() params: PositionWhereUniqueInput,
    @common.Body() body: ApplicantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applicants: {
        disconnect: body,
      },
    };
    await this.service.updatePosition({
      where: params,
      data,
      select: { id: true },
    });
  }
}
